### ISSUE TITLE
[BUG] ValueError: Currency formatting is not possible using the 'C' locale

### ISSUE THREAD

**Issue by michelpereira** [michelpereira/finerplan#1]
**Describe the bug**
When following the procedures to start the application, it doesn't run and return an error.

**To Reproduce**
Clone the repository
`https://github.com/michelpereira/finerplan`
Start the application:
`flask run --port=5001`

**Error message:**
ValueError
ValueError: Currency formatting is not possible using the 'C' locale.

Traceback (most recent call last)
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
return self.wsgi_app(environ, start_response)
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
response = self.handle_exception(e)
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
reraise(exc_type, exc_value, tb)
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
raise value
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
rv = self.dispatch_request()
File "/usr/local/anaconda3/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
return self.view_functions[rule.endpoint](**req.view_args)
File "/Users/michelpereira/Documents/workspace/finerplan/finerplan/routes.py", line 22, in overview
basic_report = reports.basic()
File "/Users/michelpereira/Documents/workspace/finerplan/finerplan/reports.py", line 80, in basic
return {'earnings': locale.currency(earnings, grouping=True),
File "/usr/local/anaconda3/lib/python3.7/locale.py", line 267, in currency
raise ValueError("Currency formatting is not possible using "
ValueError: Currency formatting is not possible using the 'C' locale.
The debugger caught an exception in your WSGI application. You can now look at the traceback which led to the error.
To switch between the interactive traceback and the plaintext one, you can click on the "Traceback" headline. From the text traceback you can also create a paste of it. For code execution mouse-over the frame you want to debug and click on the console icon on the right side.

You can execute arbitrary Python code in the stack frames and there are some extra helpers available for introspection:

dump() shows all variables in the frame
dump(obj) dumps all that's known about the object
Brought to you by DON'T PANIC, your friendly Werkzeug powered traceback interpreter.

**Comment by michelpereira** [comment]
The commit 3bed56eb2fe4d4cb2b32a721e97fac4fab037d8e fixed the issue.
